alias xup="xrdb ~/.Xresources";
alias confi3="vim ~/.config/i3/config";
alias pkglsup="pacman -Qqe > ~/Docs/pkglist.txt";
alias uni="ssh pedro@login.mathematik.uni-freiburg.de";
alias pullrefs="cd; rsync -avhr --ignore-existing pedro@login.mathematik.uni-freiburg.de:/home/pedro/refs refs;";
alias pushrefs="cd; rsync -avhr --ignore-existing refs pedro@login.mathematik.uni-freiburg.de:/home/pedro/refs;";
alias x="exit";
alias off="poweroff";
alias chinese="xdg-open ~/Documents/Chinese/Textbooks/practicalchineseT1.pdf & exit;"
alias nb_esAlg="cd ~/git/nb_esAlg; vim main.tex";
