alias xup="xrdb ~/.Xresources";
alias confi3="vim ~/.config/i3/config";
alias pkglsup="pacman -Qqe > ~/Docs/pkglist.txt";
alias uni="ssh pedro@login.mathematik.uni-freiburg.de";
alias x="exit";
alias off="poweroff";
alias egn="cd ~/git/egn; vim main.tex";
alias phd="cd ~/git/phd/updates; vim week11.tex";
alias p3="cd ~/git/adapted-extension; vim chapter2.tex";
